#!/bin/bash

args=${1:-}
if ! [ -z "${opt}"]; then killall -SIGUSR1 dunst; fi

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#b8bb26cc'  # default
T='#ebdbb2ee'  # text
W='#fb4934bb'  # wrong
V='#fabd2fbb'  # verifying

i3lock \
${args} \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y"
if ! [ -z "${opt}"]; then killall -SIGUSR2 dunst; fi
